-- =============================================================================
-- CivicLens Wave 2 — PostgreSQL 16 + PostGIS initialisation script
-- Image: postgis/postgis:16-3.4-alpine
-- Mounted at: /docker-entrypoint-initdb.d/init.sql (runs once on first start)
-- Idempotent: all statements use IF NOT EXISTS / OR REPLACE guards.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- Extensions
-- ---------------------------------------------------------------------------

CREATE EXTENSION IF NOT EXISTS postgis;       -- spatial types + indexes
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";   -- uuid_generate_v4() helper (optional)
CREATE EXTENSION IF NOT EXISTS btree_gin;     -- GIN indexes on plain scalar columns

-- ---------------------------------------------------------------------------
-- Custom ENUM types
-- ---------------------------------------------------------------------------

-- Report lifecycle (mirrors domain/report/model.go Status consts)
DO $$ BEGIN
  CREATE TYPE report_status AS ENUM (
    'created',
    'anonymized',
    'ai_analyzed',
    'dedup_checked',
    'waiting_for_review',
    'task_created',
    'rejected',
    'merged'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Task lifecycle (mirrors domain/task/model.go Status consts)
DO $$ BEGIN
  CREATE TYPE task_status AS ENUM (
    'created',
    'assigned',
    'started',
    'evidence_uploaded',
    'ai_verified',
    'completed',
    'reopened'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Priority levels (shared across reports and tasks)
DO $$ BEGIN
  CREATE TYPE priority_level AS ENUM (
    'critical',
    'high',
    'medium',
    'low'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- AI verification outcome (mirrors domain/evidence/model.go Verification consts)
DO $$ BEGIN
  CREATE TYPE ai_verification AS ENUM (
    'likely_resolved',
    'still_present',
    'needs_human'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Manager approval state (mirrors domain/evidence/model.go ApprovalXxx consts)
DO $$ BEGIN
  CREATE TYPE manager_approval AS ENUM (
    'pending',
    'approved',
    'rejected'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- RBAC roles (mirrors domain/identity/model.go Role consts)
DO $$ BEGIN
  CREATE TYPE actor_role AS ENUM (
    'citizen',
    'field_staff',
    'operator',
    'manager'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ---------------------------------------------------------------------------
-- Table: reports
-- Corresponds to domain/report/model.go Report struct.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS reports (
  -- Primary key — UUID string generated by the client or intake service
  report_id         TEXT            NOT NULL PRIMARY KEY,

  -- Source and reporter identity
  source_type       TEXT            NOT NULL,   -- citizen_mobile | staff_mobile | web
  reporter_role     TEXT            NOT NULL,   -- citizen | field_staff
  reporter_id       TEXT,                       -- omitted for anonymous citizens (KVKK)

  -- Content
  description       TEXT            NOT NULL,
  address_context   TEXT,                       -- reverse-geocoded label (neighbourhood/street)

  -- Geo-location stored as separate columns for simplicity;
  -- a PostGIS POINT is added as a generated/virtual column below.
  -- Using lat/lng columns lets the Go port stay dependency-free
  -- while still enabling spatial indexing via the geometry column.
  lat               FLOAT8,
  lng               FLOAT8,
  -- Derived PostGIS geometry (WGS-84 / SRID 4326); kept in sync via trigger.
  -- NULL when lat/lng are NULL (no location provided).
  location          GEOMETRY(Point, 4326),

  -- Image: only anonymised derivative reference — never the raw buffer (KVKK §9)
  image_ref         TEXT,
  -- KVKK assertion: raw image was NOT persisted at rest.
  raw_image_stored  BOOLEAN         NOT NULL DEFAULT FALSE,

  -- Vision pipeline linkage
  analysis_id       TEXT,

  -- Classification
  problem_type      TEXT,
  priority          priority_level,

  -- Review workflow
  review_status     TEXT,                       -- e.g. needs_review | accepted | rejected
  assigned_dept     TEXT,

  -- Deduplication
  duplicate_of      TEXT,                       -- FK to another report_id (self-referential)
  duplicate_count   INTEGER         NOT NULL DEFAULT 0,

  -- Lifecycle
  status            report_status   NOT NULL DEFAULT 'created',

  -- Timestamps (timezone-aware; Go stores RFC-3339 strings → cast on insert)
  created_at        TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
  updated_at        TIMESTAMPTZ
);

-- Trigger function: keep the PostGIS geometry column in sync with lat/lng
CREATE OR REPLACE FUNCTION sync_report_location()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.lat IS NOT NULL AND NEW.lng IS NOT NULL THEN
    NEW.location := ST_SetSRID(ST_MakePoint(NEW.lng, NEW.lat), 4326);
  ELSE
    NEW.location := NULL;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_report_location ON reports;
CREATE TRIGGER trg_sync_report_location
  BEFORE INSERT OR UPDATE OF lat, lng ON reports
  FOR EACH ROW EXECUTE FUNCTION sync_report_location();

-- Indexes on reports
CREATE INDEX IF NOT EXISTS idx_reports_status
  ON reports (status);

CREATE INDEX IF NOT EXISTS idx_reports_created_at
  ON reports (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_reports_assigned_dept
  ON reports (assigned_dept);

CREATE INDEX IF NOT EXISTS idx_reports_problem_type
  ON reports (problem_type);

CREATE INDEX IF NOT EXISTS idx_reports_priority
  ON reports (priority);

CREATE INDEX IF NOT EXISTS idx_reports_duplicate_of
  ON reports (duplicate_of)
  WHERE duplicate_of IS NOT NULL;

-- Spatial index for geo-proximity / dedup queries (GiST is the PostGIS standard)
CREATE INDEX IF NOT EXISTS idx_reports_location_gist
  ON reports USING GIST (location)
  WHERE location IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Table: tasks
-- Corresponds to domain/task/model.go Task struct.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS tasks (
  task_id       TEXT          NOT NULL PRIMARY KEY,

  -- FK to the accepted report that spawned this work order
  report_id     TEXT          NOT NULL REFERENCES reports (report_id),

  -- Assignment
  assigned_dept TEXT          NOT NULL,
  assigned_to   TEXT,                     -- user / team identifier

  -- Classification
  priority      priority_level NOT NULL DEFAULT 'medium',

  -- Lifecycle
  status        task_status   NOT NULL DEFAULT 'created',

  -- SLA string (e.g. "48h") — stored as TEXT; parse in application layer
  sla           TEXT,

  -- Timestamps
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ
);

-- Indexes on tasks
CREATE INDEX IF NOT EXISTS idx_tasks_report_id
  ON tasks (report_id);

CREATE INDEX IF NOT EXISTS idx_tasks_status
  ON tasks (status);

CREATE INDEX IF NOT EXISTS idx_tasks_assigned_dept
  ON tasks (assigned_dept);

CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to
  ON tasks (assigned_to)
  WHERE assigned_to IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tasks_created_at
  ON tasks (created_at DESC);

-- ---------------------------------------------------------------------------
-- Table: evidences
-- Corresponds to domain/evidence/model.go CompletionEvidence struct.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS evidences (
  evidence_id         TEXT              NOT NULL PRIMARY KEY,

  -- FK to the task this evidence closes
  task_id             TEXT              NOT NULL REFERENCES tasks (task_id),

  -- Vision analysis linkage (before/after comparison)
  before_analysis_id  TEXT,
  after_analysis_id   TEXT,

  -- Image: anonymised derivative only (KVKK §9)
  image_ref           TEXT,
  raw_image_stored    BOOLEAN           NOT NULL DEFAULT FALSE,

  -- Deterministic AI diff outcome
  ai_verification     ai_verification   NOT NULL DEFAULT 'needs_human',

  -- Human oversight
  manager_approval    manager_approval  NOT NULL DEFAULT 'pending',
  uploaded_by         TEXT,

  -- Timestamps
  created_at          TIMESTAMPTZ       NOT NULL DEFAULT NOW()
);

-- Indexes on evidences
CREATE INDEX IF NOT EXISTS idx_evidences_task_id
  ON evidences (task_id);

CREATE INDEX IF NOT EXISTS idx_evidences_manager_approval
  ON evidences (manager_approval);

CREATE INDEX IF NOT EXISTS idx_evidences_created_at
  ON evidences (created_at DESC);

-- ---------------------------------------------------------------------------
-- Table: audit_log
-- KVKK + accountability requirement: every status transition and significant
-- action is recorded with full actor attribution. Append-only.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS audit_log (
  -- Surrogate key; BIGSERIAL avoids UUID overhead on a high-write table
  id            BIGSERIAL     NOT NULL PRIMARY KEY,

  -- What entity changed
  entity_type   TEXT          NOT NULL,   -- 'report' | 'task' | 'evidence'
  entity_id     TEXT          NOT NULL,

  -- What happened
  action        TEXT          NOT NULL,   -- e.g. 'status_transition' | 'review_decision' | 'evidence_upload'
  old_status    TEXT,
  new_status    TEXT,

  -- Who did it (role + opaque actor identifier, never PII name in the log)
  actor_role    actor_role    NOT NULL,
  actor_id      TEXT          NOT NULL,   -- system | user_id (pseudonymised)

  -- Optional machine context
  source_ip     TEXT,                     -- stored only if legally required; omit by default
  metadata      JSONB,                    -- extensible bag for extra context (e.g. reason text)

  -- When (timezone-aware; never updatable)
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- Indexes on audit_log
CREATE INDEX IF NOT EXISTS idx_audit_log_entity
  ON audit_log (entity_type, entity_id);

CREATE INDEX IF NOT EXISTS idx_audit_log_created_at
  ON audit_log (created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_log_actor_id
  ON audit_log (actor_id);

-- GIN index on metadata for ad-hoc KVKK compliance queries
CREATE INDEX IF NOT EXISTS idx_audit_log_metadata_gin
  ON audit_log USING GIN (metadata)
  WHERE metadata IS NOT NULL;

-- =============================================================================
-- SEED DATA (disabled — uncomment for local development / integration tests)
-- =============================================================================
--
-- INSERT INTO reports (
--   report_id, source_type, reporter_role, reporter_id,
--   description, address_context,
--   lat, lng,
--   image_ref, raw_image_stored,
--   analysis_id, problem_type, priority,
--   review_status, assigned_dept,
--   status, created_at
-- ) VALUES (
--   'rep_seed_001', 'citizen_mobile', 'citizen', NULL,
--   'Yolda büyük çukur var, araç geçişi tehlikeli.',
--   'Kadıköy, Moda Caddesi',
--   41.0082, 28.9784,
--   'img_anon_seed_001', FALSE,
--   'ana_seed_001', 'road_damage', 'high',
--   'needs_review', 'Fen İşleri Müdürlüğü',
--   'waiting_for_review', '2026-06-06T10:30:00+03:00'
-- ) ON CONFLICT (report_id) DO NOTHING;
--
-- INSERT INTO tasks (
--   task_id, report_id,
--   assigned_dept, assigned_to,
--   priority, status, sla,
--   created_at
-- ) VALUES (
--   'task_seed_001', 'rep_seed_001',
--   'Fen İşleri Müdürlüğü', 'field_team_01',
--   'high', 'assigned', '48h',
--   '2026-06-06T11:00:00+03:00'
-- ) ON CONFLICT (task_id) DO NOTHING;
--
-- INSERT INTO audit_log (
--   entity_type, entity_id, action,
--   old_status, new_status,
--   actor_role, actor_id, metadata
-- ) VALUES (
--   'report', 'rep_seed_001', 'status_transition',
--   'created', 'waiting_for_review',
--   'operator', 'system',
--   '{"trigger": "intake_pipeline", "kvkk_safe": true}'::jsonb
-- );
